[simulation]
simulation_id = 1
seed = 1

#simulation grid size
nx = 202
ny = 202

#time step size
dt = 0.01

#number of time steps
nt = 100000

#mechanics configuration
mechanics_on = true
mechanics_per_potential = 10 #mechanics timesteps per potential timestep

#snapshot interval
snapshot_interval = 100

#Reaction Diffusion Model Configuration (Aliev-Panfilov model)
[voltage]
D = 0.01  # Diffusion constant
eps0 = 0.01
a = 0.1035
k = 8.0
mu1 = 0.15
mu2 = 0.15
k_T = 3.0  # Active stress constant

#Mechanical Model Configuration
[mechanics]
ks_edge = 20.0  # Edge spring constant
ks_radial = 30.0 # Radial spring constant
ks_boundary = 15.0 # Boundary spring constant
rest_edge_length = 1.0 # Rest edge length
fiber_angle = 1.0  # Fiber angle in radians
fiber_correlation = 0.1
damping = 2.0  # Damping coefficient
c_f = 0.1 # Fiber constant
padding  = 2 # How much purely mechanical padding to include