[simulation]
#simulation grid size
nx = 1002
ny = 1002

#time step size
dt = 0.01

#number of time steps
nt = 100001

#mechanics on?
mechanics_on = true

#snapshot interval
snapshot_interval = 1000

#Reaction Diffusion Model Configuration (Aliev-Panfilov model)
[voltage]
D = 0.001  # Diffusion constant
eps0 = 0.01
a = 0.1035
k = 8.0
mu1 = 0.15
mu2 = 0.15
k_T = 3.0  # Active stress constant

#Mechanical Model Configuration
[mechanics]
ks_edge = 1.0  # Edge spring constant
ks_radial = 0.0 # Radial spring constant
ks_boundary = 1.0 # Boundary spring constant
rest_edge_length = 1.0  # Rest edge length
fiber_angle = 0.0  # Fiber angle in radians
damping = 0.1  # Damping coefficient